apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterservicebrokers.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Cluster
  names:
    plural: clusterservicebrokers
    singular: clusterservicebroker
    kind: ClusterServiceBroker
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicebrokers.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: servicebrokers
    singular: servicebroker
    kind: ServiceBroker
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceclasses.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: serviceclasses
    singular: serviceclass
    kind: ServiceClass
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceclasses.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Cluster
  names:
    plural: clusterserviceclasses
    singular: clusterserviceclass
    kind: ClusterServiceClass
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceplans.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: serviceplans
    singular: serviceplan
    kind: ServicePlan
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceplans.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Cluster
  names:
    plural: clusterserviceplans
    singular: clusterserviceplan
    kind: ClusterServicePlan
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
  subresources:
    status: {}

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicebindings.servicecatalog.k8s.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: servicebindings
    singular: servicebinding
    kind: ServiceBinding
  subresources:
    status: {}

---